services:
    frontend-react:
        volumes:
            - ${PWD}/packages/frontend-react/dist:/var/www/html
            #- ${PWD}/conf/nginx-react-docker-compose.conf:/etc/nginx/conf.d/default.conf
