version: "3.5"

services:
  nomos-backend:
    volumes:
      - ../app:/var/www/html/app
      - ../migrations:/var/www/html/migrations
      - ../vhs:/var/www/html/vhs
      - ../logs:/var/www/html/logs
