services:
    rabbitmq:
        labels:
            - 'com.centurylinklabs.watchtower.enable=false'
    webhooker:
        labels:
            - 'com.centurylinklabs.watchtower.enable=false'
    backend:
        labels:
            - 'com.centurylinklabs.watchtower.enable=false'
    frontend-react:
        labels:
            - 'com.centurylinklabs.watchtower.enable=false'
    frontend-web:
        labels:
            - 'com.centurylinklabs.watchtower.enable=false'
