services:
    webhooker:
        external_links:
            - rabbitmq:rabbitmq
        networks:
            - rabbitmq

    backend-php:
        external_links:
            - rabbitmq:rabbitmq
        networks:
            - rabbitmq

networks:
    rabbitmq:
        external: true
