services:
    frontend-web:
        environment:
            VIRTUAL_HOST: membership.test.vanhack.ca,membership.devtest.vanhack.ca
            LETSENCRYPT_HOST: membership.test.vanhack.ca,membership.devtest.vanhack.ca
